### ISSUE TITLE
Windows User - No such file or directory, mkdir ...

### ISSUE THREAD

**Issue by dashawk** [tharyckgusmao/Skill-Share-Crawler---DL#1] opened 2017-10-06 01:27 UTC
Hi,

I tried to download by ID but I got an error, `No such file or directory, mkdir`. I am using windows 10 with Git Bash.

Is there a way so solve this?

**Comment by tharyckgusmao** [comment] 2017-10-06 20:37
Hi, I'm going to analyze on a w10 machine, I just tested on an arc linux machine.
As soon as I test I'll respond, if you can figure out the bug, please submit a push for the project.

Thank you

**Comment by dashawk** [comment] 2017-10-09 00:30
There must be an issue on `createFolder` calls, maybe we need to set a timeout when calling the `createFolder()`. Also, can we add an option to just use a sessionID instead of logging in to firefox? sometimes when I click login, nothing happens.

**Comment by tharyckgusmao** [comment] 2017-10-09 01:54
I'm going to test a new folder structure on a windows 10, as I did the test on the development machine and it works fine, I did about 4tb of downloading videos.

There is a problem in authentication, the google captcha seems to identify a webdriver and does not appear to break, try to authenticate facebook or oauth.

**Comment by Tasosgi** [comment] 2017-11-20 08:53
Same issue with w10

Error: ENOENT: no such file or directory, open 'D:\shareskill\master\videos\1\3 “Add Drama to Your Photos with Coloured Lighting in Photoshop”\tmp\Course Promo Vid.json'

in my HD
D:\shareskill\master\videos\13 “Add Drama to Your Photos with Coloured Lighting in Photoshop”\tmp

It seems that is trying to open wrong directory?  \videos\1\3    vs      videos\13

**Comment by tharyckgusmao** [comment] 2017-11-20 21:40
Please show me the contents of the json file, it is probably a problem with escape characters on windows, I need to treat this detail smarter.

**Comment by dashawk** [comment] 2017-11-21 01:35
It is actually trying to create the directory but the problem is that it has no permission to do so in windows machine. I tried running it with elevated privilege as admin but still the same issue.

**Comment by tharyckgusmao** [comment] 2017-11-21 01:42
I'm going to install a windows machine today and try to identify the error.

**Comment by Tasosgi** [comment] 2017-11-21 09:25
Hi, in my case json does not created because it can't found the directory(the directory never created). I create the directory manually and try again. json produced and the first video was downloaded but not the rest.

A part of the problem is the '/' one the title "1/3 “Add Drama to Your Photos with Coloured Lighting in Photoshop”"

[Course Promo Vid.zip](https://github.com/tharyckgusmao/Skill-Share-Crawler---DL/files/1490718/Course.Promo.Vid.zip)
.

**Comment by tharyckgusmao** [comment] 2017-11-21 09:28
The problem is really due to escape characters in windows. In Linux I do not have these problems.

Please tell me which category or ID you are trying to download so that I can reproduce it on my machine.

**Comment by Tasosgi** [comment] 2017-11-21 09:33
Also I try a class without '/' on the title. First video was downloaded but not the rest

![capture](https://user-images.githubusercontent.com/31473443/33064588-e7a3a266-ceae-11e7-985b-4515424e4726.JPG)

JSON
-------
[Introduction to the course course.zip](https://github.com/tharyckgusmao/Skill-Share-Crawler---DL/files/1490751/Introduction.to.the.course.course.zip)

**Comment by tharyckgusmao** [comment] 2017-11-21 10:02
I uploaded a new version with correction for escape characters.
Please test, I await feedback.

Thank you.

**Comment by dashawk** [comment] 2017-11-22 00:42
will test it now

**Comment by dashawk** [comment] 2017-11-22 00:49
finally worked fine.
![image](https://user-images.githubusercontent.com/1437205/33104225-fd9d979e-cf61-11e7-93f1-a51acd45e262.png)

**Comment by tharyckgusmao** [comment] 2017-11-22 01:06
@dashawk Thank you, thanks for the test !!

@Tasosgi 
Is there still the same error? You did the pull of the project, please download again and test. Thanks and I await feedback.

**Comment by dashawk** [comment] 2017-11-22 04:32
I tried another class with ID 1113226023 and it seemed to failed again. Maybe if there are special characters or numeric in the title, it will spit the error.

**Comment by tharyckgusmao** [comment] 2017-11-22 06:32
Hello friends, I installed a windows machine and verified the problem, I identified the lack of treatment in the names of the folders.
Please test.

The following image:

![image](https://user-images.githubusercontent.com/11817448/33113158-0ed2cc88-cf3e-11e7-9d20-56fcd89f05da.png)

**Comment by tharyckgusmao** [comment] 2017-11-22 06:35
![image](https://user-images.githubusercontent.com/11817448/33113226-8053337a-cf3e-11e7-841e-021666b7b662.png)

**Comment by Tasosgi** [comment] 2017-11-22 07:05
Hi guys, the issue with the '/' character has been resolved!   But in my case, mysteriously, only the first video is downloaded.

![257726922](https://user-images.githubusercontent.com/31473443/33114140-20512560-cf64-11e7-9828-01b739f2e918.JPG)

![263113998](https://user-images.githubusercontent.com/31473443/33114155-36079ede-cf64-11e7-897c-611110b35bfa.JPG)

**Comment by Tasosgi** [comment] 2017-11-22 07:16
Also I notice in you "Video 1/3 "Add Dream to your photos with" print screen there are ten videos. At me are nine

**Comment by noobcoder2196** [comment] 2017-11-22 09:11
Also there are some video titles with single/double quotes/question marks...basically disallowed characters. You should make a list of them (there are around 6-7) and check the presence of them in the mp4 filenames and replace them with an allowed character or simply remove them.
This is not only a windows issue, i made a 7z archive of a class on linux but when i tried to extract the program gave a filename error

**Comment by tharyckgusmao** [comment] 2017-11-22 09:49
I extract all escape characters, leaving only numbers and letters. I tested the Ids on the windows that I installed and did not show any errors.

If there is any new error please inform me the id to review.
Thanks

**Comment by Tasosgi** [comment] 2017-11-22 11:01
I will help you as much as I can with debugging.

![debug](https://user-images.githubusercontent.com/31473443/33124215-fa2e0058-cf84-11e7-90cc-b03e066fefc8.JPG)

In my case the el.video_hashed_id is null

**Comment by tharyckgusmao** [comment] 2017-11-22 12:27
I think I know what the problem is. Answer me some things.

Have you accessed the mobile app to unlock the api?

Do you have a monthly fee on the platform? you can use the 30-day trial period.

**Comment by Tasosgi** [comment] 2017-11-22 13:09
Yes, I have access with me mobile app and my trial period is still active.

At the first iteration the video_hashed_id has a value( the first video ), at next iterations video_hashed_id is NULL

**Comment by tharyckgusmao** [comment] 2017-11-22 19:32
This error next to api is not validating your account as premium, when the account has no release the videos return null, in the diagram folder of the api has the outline of the structure. Is there any possibility of you testing with another trial account?

**Comment by dashawk** [comment] 2017-11-23 00:31
I will try to test it now.

**Comment by dashawk** [comment] 2017-11-23 08:35
Wow I think its working now,
![image](https://user-images.githubusercontent.com/1437205/33155226-a48f25b4-d029-11e7-9ca2-03f5b44b4f06.png)

but I found a bug, in the selection menu to download by id or download classes, when you move it, it will automatically select the menu in the cursor position.

but all in all, the download is now working properly

**Comment by Tasosgi** [comment] 2017-11-23 09:45
You are right! My account was not premium. Thank you! Now it works like a charm!

**Comment by tharyckgusmao** [comment] 2017-11-23 17:31
Thank you all, I'll close this issue any other questions or bug say. Thank you

**Closed** 2017-11-23 17:31 UTC
Labels: bug

**Comment by NaufalAriqS21** [comment] 2018-01-11 12:11
Can someone give me step-by-step using this crawler in windows? (I am a newcomer)
